name: Go Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - '1.18.x'
          - '1.19.x'
          - '1.20.x'
          - '1.21.x'
    steps:
    - name: Fetch git repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go-version }}'

    - name: Build Go pkg
      run: go build -v ./...

