name: Go Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - oldstable
          - stable
        redis:
          - '7.x'
    steps:
    - name: Fetch git repository
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.go-version }}'

    - name: Setup Redis
      uses: shogo82148/actions-setup-redis@v1
      with:
        redis-version: ${{ matrix.redis }}
        redis-port: '6379'

    - name: Build Go pkg
      run: go build -v ./...

    - name: Run Test
      run: go test -v ./...

    - name: Run Test with -race
      run: go test -v -race ./...
